### ISSUE TITLE
COCOAログチェッカー 2.0 のリリース

### ISSUE THREAD

**Issue by ktansai** [ktansai/COVID-19-ExposeChecker#74]
## 概要
- https://github.com/ktansai/COVID-19-ExposeChecker/issues/71

であったように、COCOA2.0.0のリリースの影響で、iOSでは、今までのCOCOAのログが取得できなくなったので、COCOAログチェッカーがiOSでは使用不可になっていました。

COCOA2.0.1のリリースから、ログの出力機能がCOCOA自体に搭載されたので、このログデータを解析する機能をCOCOAログチェッカーに追加して対応したいと思っています。

今までのOSから取得できるログを解析するものから、かなり破壊的な変更になるので、COCOAログチェッカー 2.0としようと思ってます。
今まで、セマンティックバージョンでバージョンを切ってなくて、日付ビルドバージョンを使っていたので、2.0ということに特にはないですが、大きく変わったことが分かりやすいように、便宜上2.0としてリリースしようと思っています。

## 機能
今までCOCOAログチェッカーでできていた機能を提供する予定

- [x] ログを解析して、2週間以内にBluetoothの範囲内にいたCOCOA陽性登録者の総数を表示する

さらに、以下の機能もCOCOAログチェッカー2.0をリリースするタイミングで 追加したい

- [x] 接触のあった日の一覧 (今まではHASH値をコピーして、他サイトで記録のある日をある程度特定可能だったので)
- [x] 接触のあった日毎の接触数 (総数と日付が分かるので、日付ごとの記録数も自然と見たくなる)

以下はリリース時 or リリース後に追加したい機能 
(技術的に難しい訳ではないが、お知らせや、コミュニケーションが難しいかもしれないので、慎重になる部分もある)

- [ ] 2週間以上前の接触 (ログが残っている限り全て)
- [ ] 日別の接触数のグラフ

## COCOAログチェッカー1.0 との互換 / 旧版との関係
おそらく、機能的にCOCOAログチェッカー2.0が 1.0の上位互換になるので1.0を継続して使いたい人はいない気がするのですが、
念の為、1.0にアクセス出来るようにと、検討しています。
今の[release/2022.04.19.1](https://github.com/ktansai/COVID-19-ExposeChecker/releases/tag/release%2F2022.04.19.1) のwebページを、https://cocoa-log-checker.com/v1 のようなページにホストして、そこへのリンクを小さく掲載しておくのが、作業的に楽な気がしています。

(追記)
一旦、使い方や丁寧な説明を追加するよりも、
先にbeta版として、`https://cocoa-log-checker.com/beta` として先行リリースするように手配することにします。

## beta版リリースに関する必要なタスク / 実装
- [x] #75
- [x] 新フォーマットに対応 (こちらは、既にPRで対応済みで、一部要修正)

## その他リリースに関わるタスク
- [x] ログデータの取得 & ログチェッカーへの入力の方法をスクショ付きで説明する。
- [ ] 2.0との1.0との違いを説明

**Comment by ktansai** [comment]
<img width="300" alt="image" src="https://user-images.githubusercontent.com/6256289/178146829-91d40469-62b8-4d7a-9f36-73e445da0f23.png">
接触があった日と、その件数を表示

**Comment by ktansai** [comment]
@keiji お疲れ様です。まだbeta版ですが、COCOAログチェッカー2.0を 一旦リリースを行いました。
下記リンクからアクセス可能です。
https://cocoa-log-checker.com/#/beta

使ってみて、何かお気づきのことや、気になることありましたらご連絡いただけると助かります。

**Comment by keiji** [comment]
@ktansai 
ありがとうございます！
Android版のスクリーンショット、ぼくのほうで用意しましょうか？

**Comment by ktansai** [comment]
@keiji ありがとうございます。Android版のスクショ、実は撮影済みで、あとは加工する段階です(赤い枠をつけるなど) もし、何か足りない画面とかあったら、ご相談させてください。

ちなみに、Android版はCOCOAアプリから、直接クリップボードにコピーできたりしないですよね？(一旦Google Driveなど、どこかに保存して、コピーする流れになりますよね)

**Comment by keiji** [comment]
@ktansai Android版の撮影について完了しているとのこと承知しました！　ありがたい。

はい。Android版では直接クリップボードにコピーできないと理解していますが。その点少し面倒かもですね。
何かいい方法はないものか……

**Comment by ktansai** [comment]
@keiji COCOA自体側の話になってしまうので、あくまでjust ideaですが、
使い方をiOS側と挙動を揃えるという意味では、[こういう風なクリップボードへのコピー](https://stackoverflow.com/questions/238284/how-to-copy-text-programmatically-in-my-android-app
)のような実装もありえるとは思うのですが、ファイルとしてのエクスポートもできるニーズがある場合は、統一できないと思うので難しいですね。
